# Generated by Django 3.0.4 on 2020-04-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='family_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='family', to='substitute.Family'),
        ),
    ]
