# Generated by Django 3.0.4 on 2020-04-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_substitute_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitute',
            name='family_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='substitute.Family'),
        ),
    ]
