# Generated by Django 3.0.4 on 2020-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20200424_1448'),
    ]

    operations = [
    ]
