# Generated by Django 3.0.4 on 2020-05-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du produit')),
                ('nutriscore', models.CharField(max_length=1, verbose_name='Nutriscore')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('photo', models.URLField(verbose_name='Photo')),
                ('ingredients', models.URLField(null=True, verbose_name='Ingredients')),
                ('fat_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sugars_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('salt_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('saturate_fat_100g', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.Category', verbose_name='Catégorie ID')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Note',
            },
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('product_id', 'user_id'), name='unique_rating'),
        ),
    ]
