# Generated by Django 3.0.4 on 2020-05-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200501_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vote_count',
        ),
    ]
